### PR TITLE
Add a Dockerfile for project contributors

### PR DESCRIPTION
**Pull request by zkkv**
Add a Dockerfile to make it easier to contribute to the project with Docker

### CODE REVIEW

**Review by ken-matsui — COMMENTED** [review]
Thank you for working on this!  I think it makes more sense to use dev containers for development purpose, i.e., `.devcontainer/Dockerfile` along with `.devcontainer/devcontainer.json`.  What do you think?

**Comment by zkkv** [comment]
I think it can be useful, but as far as I understand it's VSCode-specific. I don't use VSCode, so I cannot reliably add this.

I would still keep the Dockerfile in the root directory because it's editor-agnostic.

**Comment by ken-matsui** [comment]
Sounds good. Can you please add the following GH action workflow to just test docker build? (please tweak if needed)

`.github/workflows/docker.yml`

```yml
name: Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build .
```

**Comment by zkkv** [comment]
I added an extra step that creates a container from the built image. Feel free to squash my commits, if you think it looks good.

**Review by ken-matsui — APPROVED** [review]
Looks great. Thank you for your time to work on this!

**Pull request merged**
